name: "Codacy coverage push"

on:
  workflow_run:
    workflows: [ "Run Tests" ]
    branches: [ "master" ]
    types: [ "completed" ]

jobs:
  push-coverage:
    name: "Push coverage"
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      ( github.event.workflow_run.event == 'push' || github.event.workflow_run.event == 'workflow_dispatch' )
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: "Install dependencies"
        uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true

      - name: "Run tests"
        run: yarn test:coverage

      - name: "Codacy push coverage"
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r ./coverage/lcov.info
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
