name: "Dependabot Auto-merge"

on:
  workflow_run:
    workflows: [ "Run Tests" ]
    branches: [ "master" ]
    types: [ "completed" ]

jobs:
  release:
    name: "Merge"
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' && github.actor == 'dependabot[bot]' &&
      github.event.workflow_run.event == 'pull_request'
    steps:
      - uses: fastify/github-action-merge-dependabot@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
