name: "Run Tests"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    name: "Lint & Build & Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: "Install dependencies"
        uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
      - name: "Lint"
        run: yarn lint
      - name: "Build"
        run: yarn build
      - name: "Test"
        run: yarn test
